url: "http://wadmiraal.net/"
markdown: rdiscount
include: [ '.htaccess' ]
permalink: /lore/:year/:month/:day/:title
paginate: 10000
paginate_path: '/lore/page:num/'
favorite: false
name: Wouter Admiraal's Blog
description: Thoughts from the strange mind of Wouter Admiraal
plugins: [ jekyll-paginate ]

